
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team02-s26-02
owner: ucsb-cs156-s26
repo_name: team02-s26-02
pull_requests: [{"author":{"id":"U_kgDOCMR-Zg","is_bot":false,"login":"Andrew-UCSB","name":""},"headRefName":"Andrew-RR-IntegrationTest","number":133,"title":"Add Integration Tests for Recommendation Requests","url":"https://github.com/ucsb-cs156-s26/team02-s26-02/pull/133"},{"author":{"id":"U_kgDOBztTrQ","is_bot":false,"login":"Makkerel","name":"Kevin "},"headRefName":"Kevin-EndtoEndUCSBOrganization","number":132,"title":"added end to end test for UCSBOrganization","url":"https://github.com/ucsb-cs156-s26/team02-s26-02/pull/132"},{"author":{"id":"MDQ6VXNlcjc5NDc1MDQx","is_bot":false,"login":"Bombboox","name":"Arman Petrosyan"},"headRefName":"Articles-End2End","number":130,"title":"Articles End to End Test","url":"https://github.com/ucsb-cs156-s26/team02-s26-02/pull/130"},{"author":{"id":"MDQ6VXNlcjc5NDc1MDQx","is_bot":false,"login":"Bombboox","name":"Arman Petrosyan"},"headRefName":"Articles-Team03","number":123,"title":"Articles Integration Test","url":"https://github.com/ucsb-cs156-s26/team02-s26-02/pull/123"}]
