
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team02-s26-02
owner: ucsb-cs156-s26
repo_name: team02-s26-02
pull_requests: [{"author":{"id":"U_kgDOB3D2TQ","is_bot":false,"login":"just-in-fan","name":"Justin Fan"},"headRefName":"jf-team03-End-to-End","number":104,"title":"Created End to End Test for UCSBDiningCommonsMenuItems","url":"https://github.com/ucsb-cs156-s26/team02-s26-02/pull/104"},{"author":{"id":"U_kgDOB3D2TQ","is_bot":false,"login":"just-in-fan","name":"Justin Fan"},"headRefName":"jf-team03","number":103,"title":"Created Integration tests for UCSBDiningCommonsMenuItems for GET and POST","url":"https://github.com/ucsb-cs156-s26/team02-s26-02/pull/103"},{"author":{"id":"MDQ6VXNlcjc5NDc1MDQx","is_bot":false,"login":"Bombboox","name":"Arman Petrosyan"},"headRefName":"Articles-PagePlaceholders","number":102,"title":"Articles Placeholders","url":"https://github.com/ucsb-cs156-s26/team02-s26-02/pull/102"},{"author":{"id":"U_kgDOC5DYGg","is_bot":false,"login":"KawaiiKai132","name":""},"headRefName":"Kai-MenuItemReview-index-page","number":100,"title":"Kai menu item review index page","url":"https://github.com/ucsb-cs156-s26/team02-s26-02/pull/100"},{"author":{"id":"U_kgDOC5DYGg","is_bot":false,"login":"KawaiiKai132","name":""},"headRefName":"Kai-MenuItemReview-create-page","number":98,"title":"Kai menu item review create page","url":"https://github.com/ucsb-cs156-s26/team02-s26-02/pull/98"},{"author":{"id":"U_kgDOBztTrQ","is_bot":false,"login":"Makkerel","name":"Kevin "},"headRefName":"Kevin-UCSBOrganizationCreatePage","number":95,"title":"Kevin ucsb organization create page","url":"https://github.com/ucsb-cs156-s26/team02-s26-02/pull/95"}]
