
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team02-s26-02
owner: ucsb-cs156-s26
repo_name: team02-s26-02
pull_requests: [{"author":{"id":"U_kgDOBztTrQ","is_bot":false,"login":"Makkerel","name":"Kevin "},"headRefName":"Kevin-copyCRUDUCSBOrganization","number":63,"title":"Copied over CRUD from team01","url":"https://github.com/ucsb-cs156-s26/team02-s26-02/pull/63"},{"author":{"id":"U_kgDOB3D2TQ","is_bot":false,"login":"just-in-fan","name":"Justin Fan"},"headRefName":"jf-UCSBDiningCommonsMenuItem-backend","number":62,"title":"Copied over backend for UCSBDiningCommonsMenuItems from team01","url":"https://github.com/ucsb-cs156-s26/team02-s26-02/pull/62"},{"author":{"id":"U_kgDOCMR-Zg","is_bot":false,"login":"Andrew-UCSB","name":""},"headRefName":"Andrew-CRUD","number":61,"title":"Copied CRUD backend files for Recommendation Request from team01","url":"https://github.com/ucsb-cs156-s26/team02-s26-02/pull/61"}]
